import math, random

// func add(first int, second int) -> int {
func add(first int, second int) { // review return syntax later
	// return first + second
	print(first, "plus", second, "is", first + second)
}

add(3, 2)
print(3 * false)
// add(1, "2") // throws an error, as it should
