import math, random

func add(first int, second int) -> int {
	print("adding", first, "and", second)
	return first + second
}

print(3, "plus", 2, "is", add(3, 2))
print(3 * true)
add(1, "2") // throws an error, as it should
